def quizzDate():
    date = {"Perguntas": ['Mohji é um pirata e o imediato dos Piratas do Buggy, bem como um membro da Aliança do Buggy e Alvida',
                          '[GLA] Você precisa vencer com um time de lutadores para completar a conquista dos Piratas do Buggy',
                          '[GLA] Tamanegi, um dos Piratas do Usopp, dá algumas missões em Syrup Village',
                          '[GLA] Você precisa vencer com um time de especialista para completar a conquista dos black cat',
                          '19:56 Ghus: Só morre quem upa',
                          'Yasopp nasceu no East Blue, em Syrup Village',
                          'Portgas D. Ace é filho do Gol D. Roger',
                          '[GLA] Ninjin, um dos Piratas do Usopp, dá algumas missões em Syrup Village',
                          '[GLA] O Kit de Reparo 1.0 restaura 12.000 pontos de vida do seu navio em 20 segundos',
                          '[GLA] O Kit de Reparo 4.0 restaura 54.000 pontos de vida do seu navio em 20 segundos',
                          '[GLA] O Kit de Reparo 4.0 restaura 2700 pontos de vida do seu navio por segundo',
                          'Tashigi nasceu no East Blue',
                          '[GLA] É possível preparar alguns alimentos na casa da Nojiko',
                          'Eiichiro Oda é o criador do One Piece',
                          'Crocodile é o único dos Shichibukai originais a possuir uma Fruta do Diabo do tipo Logia',
                          'Ghus ta com viado',
                          'Master shake é hacker ',
                          'Buggy era um Shichibukai',
                          'A recompensa da Jewelry Bonney é de 140,000,000 de berry',
                          '[GLA] Erros no jogo devem ser reportados usando o atalho CTRL + R',
                          'Mr.1 comeu a Supa Supa no Mi',
                          'Vasco Shot é o capitão do oitavo navio, liderando a oitava frota do Teach',
                          '[GLA] É possível criar Medalhas Dinâmicas de Bronze por 5 Moedas Piratas no Mercado Negro',
                          'Baby Five nasceu no North Blue',
                          "A segunda recompensa conhecida do Capone 'Gang' Bege era de 300,000,000 de berry",
                          '[GLA] Em regra, emotes são desbloqueados no nível 25',
                          'Pekoms tem uma impressionante recompensa de 330,000,000 de berry',
                          'Trebol é usuário de Haki do Armamento e da Observação',
                          'O nome verdadeiro da Miss Merrychristmas é Drophy',
                          'Zephyr é um personagem non-canon',
                          'A recompensa do Tamago é de 429,000,000 de berry',
                          'Avalo Pizarro é o capitão do quarto navio, liderando a quarta frota do Teach',
                          'Pearl é o comandante da segunda unidade dos Piratas do Krieg',
                          'Após a morte do Barba Branca, o Barba Marrom fugiu e assumiu o controle de Foodvalten',
                          'Existem Frutas do Diabo que ainda não foram catalogadas e, portanto, desconhecidas',
                          '[GLA] O uso do Kit de Reparo é interrompido se você receber qualquer ataque de um inimigo',
                          'Van Augur nasceu no East Blue',
                          'A alcunha do Doc Q, "Shinigami" ou deus da morte, vem do fato dele gostar de brincar com a vida das pessoas, assim como um shinigami',
                          'Buggy foi o primeiro vilão a aparecer na série que era usuário de uma Fruta do Diabo. Ele foi também o primeiro usuário de uma fruta do diabo com quem Luffy lutou',
                          '[GLA] O Kit de Reparo 2.0 restaura 1125 pontos de vida do seu navio por segundo',
                          '[GLA] Samui Island é recomendada para jogadores do level 20 a 28 no minimapa do jogo',
                          'A recompensa do Mr.2 é de 32,000,000 de berry',
                          'Dalton nasceu em Drum Island',
                          'Buggy tem a menor recompensa entre os Shichibukai',
                          'Vergo foi o primeiro Corazón',
                          'A recompensa de Mont Blanc Cricket é de 25,000,000 de berry',
                          'O verdadeiro nome do Mr.2 é Bentham',
                          'Rob Lucci nasceu na Grand Line',
                          "Kin'emon comeu a Fuku Fuku no Mi",
                          'A comida favorita da Sugar é uva',
                          'Jango é um marinheiro e ex-imediato do capitão Kuro',
                          "A habilidade 'Usopp's Fear' concede a ele velocidade e defesa",
                          'Ace realmente nasceu em Baterilla',
                          'Crocus nasceu na Grand Line',
                          'A primeira recompensa do Chopper foi de 50 de berry',
                          'Masira nasceu no North Blue',
                          'Boa Hancock usa Haki do Rei',
                          'Há seis níveis em Impel Down',
                          'O verdadeiro nome do Mr.3 é Galdino',
                          'Vergo conhece o Doflamingo desde quando ele era uma criança',
                          'Donquixote Doflamingo era capitão dos Piratas Donquixote',
                          'A atual Recompensa da Nami é de 66,000,000 de berry',
                          'Vinsmoke Reiju é usuária de Akuma no Mi',
                          'Sanji nasceu no north blue',
                          'A Yubashiri (Espada de Zoro) Enferrujou',
                          'Kuro, também conhecido por seu apelido de Klahador, é o capitão dos Piratas Black Cat',
                          'Primeiro beijo do Sanji foi com a Pudding',
                          'Existem 8 Henchmans no black market',
                          'A recompensa de Miss Doublefinger é de 35,000,000 de berry',
                          'A segunda recompensa de Monkey D. Luffy foi de 100,000,000 de berry',
                          '[GLA] O jogo está traduzido para os seguintes idiomas: Inglês,Português,Espanhol e Polonês',
                          'Rob Lucci enfrentou Sabo depois do Timeskip',
                          'A Recompensa de Curly Dadan é 7,800,000 de berry',
                          'O canhão do Mr.4 comeu uma fruta do diabo e se tornou um cachorro',
                          'O cabelo do Trebol é preto',
                          'Joy Boy foi mencionado no Ryugu Poneglyph lido por Nico Robin na floresta do Oceano',
                          'Joy Boy tentou levantar a Noah com a ajuda de Poseidon, mas ele quebrou sua promessa com a ilha dos Tritões',
                          'Lucky roo é um membro dos piratas do Ruivo',
                          'Houve um Crossover entre One Piece e Dragon Ball Z no anime',
                          "[GLA] Urouge pode usar a habilidade Pray para curar aliados e remover condições de lentidão ou queimadura",
                          'A atual recompensa de Marshall D. Teach é de 2,247,600 de berry',
                          'A akuma no mi do Pika é do tipo Paramecia',
                          'O sonho de Crocodile era ser Rei dos Piratas',
                          'Portgas D. Ace é filho de Rouge',
                          'Hancock é a primeira personagem mulher da série capaz de usar todas as três formas de Haki',
                          '[GLA] Para evoluir um personagem de 1 para 5 estrelas é necessário 840 fragmentos no total',
                          'Porco Gourmet é o prato mais demorado para cozinhar em baratie levando 9 minutos',
                          '[GLA] Bege libera uma habilidade no level 100',
                          'Silvers Rayleigh tem uma esposa no Arquipelago Sabaody',
                          'Marco nasceu na grand line',
                          'A cor do cabelo do Edward Newgate (Barba Branca) era loiro',
                          '[GLA] Você completa com um time de especialistas a conquista do Black Cat',
                          'Tralfagar Law comeu a Ope Ope no Mi',
                          'Kizaru comeu a Pika Pika no Mi',
                          'Tralfagar Law perdeu um braço no arco de Dressrosa',
                          'Gol D. Roger foi o primeiro rei dos piratas',
                          '[GLA] Sapi é o NPC que vende atum em Loguetown',
                          'Mr.3 Wax é tão duro quanto ferro',
                          'Aokiji possui uma fruta do diabo do tipo Logia',
                          'Pagaya é pai de Conis',
                          '[GLA] Em Conomi Island tem os seguintes monstros: Wolf,Mole e Baby Mole',
                          'Magellan nasceu na Grand Line',
                          'Sanji em sua infância teve a mesma dubladora do Chopper',
                          "[GLA] Luffy quando usa sua habilidade 'Preparation' Se torna mais veloz e seu próximo ataque da mais dano",
                          'Pappag é uma estrelar do mar',
                          'Pappag é uma estrela do mar que é mascote de Camie e professor. Ele é o criador da linha de moda Criminal e é mentor de Camie para ser uma designer de moda',
                          'O nome verdadeiro da Miss Valentine e Mikita',
                          'A irmã do Arlong é conhecida',
                          'Zephyr é o único Almirante que não comeu uma Fruta do Diabo',
                          'Barba Negra nasceu na Grand Line',
                          'Ton Ton no Mi é uma versão superior da Kilo Kilo no Mi',
                          '[GLA] O Kit de Reparo 2.0 restaura 22.500 pontos de vida do seu navio em 20 segundos',
                          'Shanks é um membro dos Yonko que governam o novo mundo e é capitão dos piratas do Ruivo',
                          'Caribou nasceu no North Blue',
                          'Dracule Mihawk teve 2 dubladores no anime',
                          '[GLA] É possível criar medalhas dinâmicas de ouro por 20 moedas piratas no mercado negro',
                          '[GLA] É possível criar medalhas dinâmicas de prata por 10 moedas piratas no mercado negro',
                          '[GLA] Genzo vende bandana de tritão, calça de tritão, anel do mar e turbante do mar por 5200 berry cada',
                          'Brook era capitão dos piratas rumbar',
                          '[GLA] Em Cocoyasi tem os seguintes monstros: Alligators, Fishmans, Panthers, Baby Octopus e Wolves',
                          '[GLA] Nami não pode usar a habilidade Fata Morgana enquanto Mirage Tempo estiver ativa',
                          'Buggy é capitão dos piratas do Buggy e também colíder da aliança do Buggy e Alvida',
                          '[GLA] Chabo é o nome da criança que a Nojiko pede para ajudar no Arlong Park',
                          'Gecko Moriah tem a recompensa de 320,000,000 de berry',
                          'Shoujou nasceu no North Blue',
                          '[GLA] Cocoyasi Village é recomendada para jogadores de nivel 50-60 no minimapa do jogo',
                          'A comida favorita da Nezumi é queijo',
                          'A rumble Ball dura 3 minutos',
                          'A recompensa de Capone Gang Bege é de 300,000,000 de berry',
                          'O smoker assim como o Fujitora, tenciona acabar com o sistema de Shichibukais',
                          'A Boa Hancock é a imperatriz de Amazon Lily, e por isso é conhecida como Imperatriz Pirata',
                          'Foxy nasceu em South Blue',
                          'Mr.5 nasceu no South Blue',
                          '[GLA] Você pode ouvir o Chouchou latindo ao falar com ele',
                          'A recompensa de Mr.5 é de 10,000,000 de derry',
                          'Mr.9 nasceu em Weast Blue',
                          'A recompensa de Miss Goldenweek é de 29,000,000 de Berry',
                          'Caso o One Piece fosse ambientado no mundo real, o Luffy seria do Brasil',
                          'Gum-Gum Fruit é o nome oficial da Fruta do Diabo do Luffy em inglês',
                          'A mãe do Monkey D. Luffy ainda não foi revelada',
                          'Boa Hancock tem referencias com a mitologia grega',
                          'Kuma já foi um rei',
                          '[GLA] Bartolomeu Kuma lê sua bíblia durante sua animação do seu emote',
                          'A recompensa do Kuma é de 296,000,000 de berry',
                          'Doflamingo era um Tenryubito.',
                          'O nome verdadeiro do Mr.5 é Gem',
                          'Monet comeu a Yuki Yuki no Mi',
                          'A Gura Gura no Mi é também conhecida como a mais forte das Paramecia, igual a uma Logia. Sengoku afirmou que ela é poderosa o suficiente para destruir o mundo',
                          'Rosinante comeu a Nagi Nagi no Mi',
                          'Foxy comeu a Noro Noro no Mi',
                          'Giolla criou Dellinger praticamente sozinha, fazendo com que ele pensasse que era uma menina, razão pela qual ele se tornou tão feminino',
                          'Caesar comeu a Gasu Gasu no Mi',
                          'Kuma é conhecido como Tirano',
                          '[GLA] Você precisa vencer com uma equipe de mulheres, para completar a conquista da Pirata Armada',
                          'Teach foi o responsável por cicatrizar o olho de Shanks com sua arma de garras',
                          'A recompensa do Dellinger era de 15,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado Shichibukai',
                          'Caesar liberou um gás não letal em Punk Hazard',
                          'A recompensa do Kuro é de 16,000,000 de berry',
                          'A recompensa dos irmãos Nyaban é de 7,000,000 de berry',
                          'Lucky Roo nasceu no South Blue',
                          'Monkey D. Luffy nasceu em Foosha Village',
                          '[GLA] A habilidade Preparation aumenta a velocidade do Luffy por 4 segundos e concede bônus de força no próximo ataque',
                          'Luffy tem uma fruta do Diabo do tipo Paramecia',
                          'Brook é mais alto do que Franky depois do TimeSkip',
                          'A quarta recompensa de Monkey D. Luffy é de 400,000,000 de berry',
                          "[GLA] O nome de todas as habilidades do Capone Gang Bege começam com a letra 'C', exceto a Big Father",
                          '[GLA] Kuro causa 20% a mais de dano atacando o inimigo pelas costas',
                          '[GLA] É possível criar medalhas dinâmicas de diamante por 50 moedas piratas no mercado negro',
                          '[GLA] A rotação muda toda sexta-feira',
                          '[GLA] Whale Shark é considerade um monstro nível 3',
                          '[GLA] Em regra, a quinta habilidade do personagem é desbloqueada no nível 30',
                          'A recompensa do Senor Pink era de 58,000,000 de berry antes de congelada em razão do Doflamingo ter se tornado Shichibukai',
                          "Koala é uma 'oficial' do exercito revolucionario",
                          "O nome do Navio que Mr.5 e a Miss Valentine usavam em suas operações era 'Pop Rock Candy'",
                          'O nome verdadeiro da Miss Goldenweek é Marianne',
                          '[GLA] Monkey D. Luffy NÃO pode quebrar paredes com a habilidade Gomu Gomu no Ono',
                          'Chopper foi o sexto membro a entrar na tripulação dos Chapéus de Palha',
                          'Kalgara foi revelado como um usuário de Haki da Observação',
                          '[GLA] O jogo Grand Line Adventures foi lançado em Agosto de 2018',
                          'Boa Hancock é a capitã das Piratas Kuja e a única mulher membro dos Shichibukai',
                          "O navio que a Hancock e as piratas Kuja navegam é chamado de 'Perfume Snake'",
                          'Hody Jones e seus companheiros não possuem recompensa',
                          'Pekoms tem uma Fruta do Diabo do tipo Zoan',
                          'Akainu tem o mesmo dublador do Krieg',
                          'Miss Doublefinger nasceu na Grand Line',
                          'Stussy nasceu na Grand Line',
                          'Pell nasceu em Alabasta',
                          "Mr.3 agora é reconhecido como um 'executivo' dos Piratas do Buggy",
                          'Zeff perdeu sua perna direita para salvar Sanji',
                          '[GLA] Em regra, a quarta habilidade do personagem é desbloqueada no nível 20',
                          'Momoo agora é oficialmente considerado um animal de estimação dos Piratas do Caribou',
                          'Koala está lutando no Exército Revolucionário para mudar o mundo de uma forma que os Tritões e as Sereias sejam tratados como pessoas normais',
                          'Kureha nasceu em Drum Island',
                          'Demaro Black, Manjaro, Chocolat, Drip, Turco, Cocoa, Mountblutain e Nora Gitsune são os nomes verdadeiros da falsa tripulação dos Chapéus de Palha',
                          '[GLA] Eustass Kid pode construir pontes com a habilidade Magnetic Pull',
                          'Portgas D. Ace era um usuário de Haki do Rei',
                          '[GLA] Sanji não pode ser seduzido pelas mulheres enquanto o Diable Jamble estiver ativado',
                          'Emporio Ivankov nasceu na Grand Line',
                          'Atualmente Moria é o único Shichibukai conhecido (atual ou antigo) sem uma alcunha conhecida',
                          'Monet e Sugar são irmãs',
                          'Laffitte cresceu no West Blue, onde se tornou xerife',
                          '[GLA] Boa Hancock não pode petrificar o Monkey D. Luffy',
                          "[GLA] Sayuri, Asuya e Chieri são nomes de NPC's do Baratie",
                          'Hody Jones é o capitão dos Novos Piratas Homens-Peixe',
                          'Otohime tinha um Haki da Observação muito desenvolvido, o que a permitia entender profundamente a emoção dos outros',
                          '[GLA] Existem Bronze berry, Silver berry, Gold berry e Platinum berry',
                          'A recompensa do Chew é de 5,500,000 de berry',
                          'O nome verdadeiro do Barba Marrom é Chadros Higelyges',
                          'Benn Beckman nasceu no North Blue',
                          '[GLA] Kumo Island é recomendado para jogadores do level 64 a 72 no minimapa do jogo',
                          'Gol D. Roger nasceu em Loguetown',
                          'Machvise comeu a Ton Ton no Mi',
                          'Scratchmen Apoo é da tribo longarm, um infâme pirata com tema de música e capitão dos Piratas On Air',
                          'Tsuru comeu a Woshu Woshu no Mi',
                          'Alvida é a antiga capitã dos Piratas da Alvida',
                          'Franky é o oitavo membro da tripulação dos Chapéus de Palha',
                          'O dragão contra o qual Luffy e os outros lutaram em Punk Hazard foi criado artificialmente por VEGAPUNK em um laboratório em Punk Hazard',
                          '[GLA] Carne de Porco Gourmet é a comida mais demorada para cozinhar no Baratie. Demora 9 minutos',
                          '[GLA] Em regra, a terceira habilidade do personagem é desbloqueada no nível 12',
                          '[GLA] Em Cocoyasi Village você pode comprar Laranja do NPC pelo valor de 42 berries cada',
                          'A comida favorita de Marco é abacaxi',
                          'Benn Beckman é o personagem mais inteligente que apareceu na saga do East Blue',
                          'O aniversário da Miss Merry Christmas é no natal, por razões óbvias',
                          "O nome do navio do Mr.2 era 'Swanda Express'",
                          "O nome do navio que os Piratas Donquixote usaram nos dias deles no North Blue era 'Numancia Flamingo'",
                          'A recompensa do Machvise era de 11,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai',
                          'A recompensa do Zoro era maior que a do Sanji',
                          'Arlong é o único indivíduo conhecido que foi libertado de Impel Down',
                          "Kin'emon é usuário de Haki da Observação e do Armamento",
                          '[GLA] Skins de navio estão disponíveis somente para navios de nível dois ou maior',
                          'A maior recompensa conhecida é de 2,247,600,000 de berry',
                          'Kuzan nasceu no South Blue',
                          'Issho comeu a Zushi Zushi no Mi, que o permite manipular a gravidade',
                          'Hatchan é um ex-oficial dos Piratas do Arlong e membro dos Piratas do Sol antes disso',
                          'Os Yeti Cool Brothers são parte de uma subespécie desconhecida de gigantes',
                          'Pica tem uma fruta do diabo do tipo Paramecia',
                          'Shiryu é o capitão da segunda frota do Teach',
                          '[GLA] Há uma piscina em Shells Town, dentro da Base da Marinha',
                          'Lucky Roo pode parecer gordo e lento, mas na verdade ele é um lutador muito ágil e rápido',
                          'Barba Negra é um almirante dos Piratas do Barba Negra e membro dos Yonko',
                          'A recompensa do Demaro Black é de 26,000,000 de berry',
                          'A recompensa da Miss Merry Christmas é de 14,000,000 de berry',
                          'Dizem que Yasopp pode atirar na antena de uma formiga de muito longe',
                          '[GLA] Snowball é o nome de um coelho em Samui Island',
                          'Usopp foi o terceiro membro a entrar na tripulação dos Chapéus de Palha',
                          'A recompensa do Fisher Tiger era de 230,000,000 de berry',
                          'A recompensa do Kuroobi é de 9,000,000 de berry',
                          'Após os eventos em Punk Hazard, Smoker se tornou oficialmente o líder da G-5',
                          '[GLA] A habilidade Liberation, do Marshall D. Teach, tem 2 segundos de tempo de recarga e 18 de poder',
                          'A primeira recompensa do Monkey D. Luffy foi de 30,000,000 de berry',
                          '[GLA] Dracule Mihawk desacelera seus próprios aliados com a habilidade Taka no Me',
                          'A recompensa da Miss Valentine é de 7,500,000 de berry',
                          'Aisa nasceu com um Haki da Observação avançado',
                          '[GLA] Você pode encontrar 9 entradas para o Mercado Negro no East Blue',
                          'Gryphon é o nome da espada do Shanks',
                          '[GLA] Portgas D. Ace é um personagem Diamante',
                          'A recompensa do Diamante era de 99,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai',
                          'Tsuru nasceu no North Blue',
                          'Demaro Black, capitão dos Falsos Chapéus de Palha, nasceu no East Blue',
                          'Koala era um membro dos Piratas do Sol',
                          '[GLA] Island of Rare Animals é recomendada para jogadores do level 40 a 52 no minimapa do jogo',
                          'Antes dos eventos da guerra, Doc Q tinha uma impressionante recompensa de 72,000,000 de berry',
                          '[GLA] Para melhorar um personagem de 1 para 5 estrelas você precisa usar 840 medalhas no total',
                          '[GLA] Orange Town é recomendada para jogadores do level 23 a 30 no nimimapa do jogo',
                          '[GLA] Jutte Blow, a habilidade do Smoker, silencia somente usuários de Fruta do Diabo',
                          'Objetos podem comer Frutas do Diabo',
                          'A recompensa do Trebol era de 99,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai',
                          'Urouge é também conhecido como Mad Monk. Ele é um pirata de uma ilha do céu e capitão dos Piratas Fallen Monk',
                          'Tamago é membro da tribo dos Pernas Longas',
                          'A recompensa do Pica era de 99,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai',
                          'Aladdin já foi um escravo',
                          '[GLA] Golden Hull é o nome de uma skin de navio',
                          'Foi confirmado que Usopp despertou o Haki da Observação durante o arco de Dressrosa',
                          'Doflamingo é usuário do Haki da Observação, Armamento e do Rei',
                          '[GLA] Pearl é o primeiro boss nas missão da Armada Pirata',
                          'Barba Negra acredita legitimamente que os sonhos dos homens nunca morrerão',
                          "Trafalgar Law nomeou sua tripulação por causa do Corazón, como homenagem ao seu nome e porque ele 'mudou seu coração' para melhor",
                          '[GLA] Você não pode trocar seus equipamentos em batalha',
                          'Trebol foi o primeiro a encontrar a Ito Ito no Mi quando era um criminoso',
                          '[GLA] O Talismã da Aranha é um item que pode ser usado por todas as classes',
                          '[GLA] Baratie é recomendado para jogadores do level 42 a 52 no minimapa do jogo',
                          '[GLA] Você precisa vencer com um time de suportes para completar a conquista dos Piratas do Arlong',
                          'Issho nasceu na Grand Line',
                          'Sanjuan Wolf tem uma fruta do diabo que o permite aumentar o próprio tamanho',
                          'A recompensa do Foxy é de 24,000,000 de berry',
                          'Jinbe é oficialmente o décimo membro dos Piratas do Chapéu de Palha',
                          '[GLA] Você pode usar o atalho ALT + ENTER para colocar o jogo em tela cheia',
                          'Miss Goldenweek nasceu no North Blue',
                          'O nome verdadeiro do Hatchan é Hatchan',
                          'Crocodile foi o primeiro oponente a derrotar Luffy em uma batalha',
                          'Masira e Shoujo têm uma recompensa de 23,000,000 e 36,000,000 de berry, respectivamente',
                          '[GLA] Syrup Village é a ilha com o maior número de entradas de doca no East Blue',
                          'Catarina Devon caça qualquer mulher que ela acha atraente e decapita a cabeça delas para adicioná-las à sua coleção pessoal',
                          'Miss Goldenweek fez dupla com o Mr.3 em razão das habilidades dela de pintar as criações de cera, tornando-as mais realistas',
                          "O principal navio do Exército Revolucionário é chamado de 'Viento Granma'",
                          'Lucky Roo foi um dos primeiros membros a entrar na tripulação do Shanks após ele formar os Piratas do Ruivo',
                          'Shanks tem uma cicatriz no olho esquerdo',
                          '[GLA] Existem Cows, Pigs, Chickens e Sheeps em Foosha Village',
                          'Capone Gang Bege é capitão do Fire Tank Pirates e também um dos doze piratas classificados como a Pior Geração',
                          'Wapol é o primeiro rei mostrado na série',
                          'Bellemere encontrou a Nami e a Nojiko no Reino de Oykot, no East Blue',
                          'Antes dos eventos da guerra, Van Augur tinha uma impressionante recompensa de 64,000,000 de berry',
                          'Antes dos eventos da guerra, Jesus Burgess tinha uma recompensa de 20,000,000 de berry',
                          'Mr.4 nasceu na Grand Line',
                          '[GLA] Cabaji tem a menor velocidade de movimento base do jogo',
                          '[GLA] Você precisa vencer com um time de cortantes para completar a conquista dos Piratas da Alvida',
                          'Em termos simples, Haki é a habilidade de sentir energia espiritual (Kenbunshoku), usar força vital (Busoshoku) e dominar inimigos (Haoshoku)',
                          'Gedatsu (um dos sacerdotes de Enel) agora gerencia um Resort de águas termais em Alabasta',
                          'A Ope Ope no Mi é também chamada de Fruta do Diabo Suprema, devido à sua habilidade de conceder vida eterna',
                          '[GLA] É possível reparar os equipamentos do seu barco nas Docas',
                          "O aniversário da Miss Valentine é no Valentine's Day, por razões óbvias",
                          'Robin foi o sétimo membro a entrar na tripulação dos Chapéus de Palha',
                          '[GLA] Personagens envenenados pela Reiju recebem 50% menos cura de suportes',
                          'Issho decidiu se cegar porque havia muitas coisas que ele não queria ver',
                          'Zoro empunhou mais de 8 espadas diferentes no anime',
                          'Shakky ajudou a abrigar as Gorgon Sisters depois que elas escaparam dos Nobres Mundiais junto com Gloriosa e Rayleigh',
                          'Sabo comeu a Mera Mera no Mi',
                          '[GLA] Você pode comprar duas abas extras do Stash. A primeira custa 150.000 berry e a segunda 300.000 berry',
                          'A recompensa do Daz Bones é de 75,000,000 de berry',
                          'Bellamy se retirou oficialmente como um pirata e agora se dedica a pintura de bandeiras',
                          '[GLA] O Kit de Reparo 3.0 restaura 36.000 pontos de vida do seu navio em 20 segundos',
                          'Sogeking na verdade é o Usopp',
                          '[GLA] Boa Hancock pode transformar os inimigos em pedra por 7 segundos com a habilidade Mero Mero Mellow',
                          'Após ser diagnosticado com sua doença, Gol D. Roger levou três anos para encontrar o One Piece',
                          'Jesus Burgess é o timoneiro dos Piratas do Barba Negra',
                          'Bartholomew Kuma é um Shichibukai e um ex-oficial do Exército Revolucionário',
                          'Shanks nasceu no West Blue',
                          'Marco comeu a Tori Tori no Mi, tipo: Fênix, uma Zoan Mítica',
                          'Arlong era o capitão dos Piratas do Arlong e tinha a maior recompensa do East Blue antes de ser derrotado pelo Monkey D. Luffy',
                          '[GLA] Chopper ganha defesa bônus durante a habilidade Walk Point',
                          'O verdadeiro nome da Miss Doublefinger é Zala',
                          'Caso o Governo Mundial soubesse que o Crocodile era o chefe da Baroque Works, a recompensa dele seria no mínimo dobrada para 162,000,000 de berry',
                          'Mr.2 tem o mesmo dublador do Franky e do Jango',
                          'Sanjuan Wolf nasceu no West Blue',
                          'Laffitte nasceu no West Blue',
                          '[GLA] Trafalgar Law pode quebrar paredes com a habilidade Injection Shot',
                          "Kin'emon pode se comunicar através de peidos, fazendo eles soarem como a linguagem humana",
                          'A recompensa atual do Marshall D. Teach é de 2,247,600,000 de berry',
                          'Kid e Killer são amigos de infância. Juntos, formaram os Piratas do Kid',
                          'Shiryu nasceu na Grand Line',
                          'A recompensa do Mr.3 é de 24,000,000 de berry',
                          'Laboon é macho',
                          'Em razão dos seus crimes, Sanjuan Wolf foi preso em Impel Down. O modo que eles encontraram para mantê-lo preso foi através de uma cela gigante no level 6',
                          '[GLA] Há um baú escondido atrás da mansão da Kaya',
                          "O nome dos navios do Masira e do Shoujo são 'Victory Hunter' e 'Utan Sonar', respectivamente",
                          'A recompensa do Gin é de 12,000,000 de berry',
                          'Desde quando Mr.1 era uma criança, ele sempre quis ser um herói. Todavia, os ideais dele se distorceram bastante, transformando-o em um assassino implacável',
                          '[GLA] Loguetown é recomendada para jogadores do level 60 a 70 no minimapa do jogo',
                          'Miss Goldenweek não comeu uma Fruta do Diabo',
                          '[GLA] Você precisa alimentar um prisioneiro na Quest da Rika',
                          'A recompensa do Jinbe era de 250,000,000 de berry antes dele se tornar um Shichibukai',
                          'Issho é um Almirante da Marinha',
                          '[GLA] Quando o Alligator selvagem morre, o sangramento aplicado por ele perde o efeito',
                          'A recompensa do Mr.4 é de 3,200,000 de berry',
                          '[GLA] Pearl não pode usar nenhuma habilidade enquanto Iron Wall estiver ativo',
                          'Benn Beckman é o vice-capitão dos Piratas do Ruivo',
                          'Basil Hawkins é um pirata infâme do North Blue conhecido como o Mago e capitão dos Piratas do Hawkins',
                          'Zeus é um personagem do One Piece',
                          'Em alguns fillers, os personagens foram feitos pelo próprio Oda',
                          '[GLA] Reiju pode usar sua habilidade Pink Tornado para se livrar de imobilizações',
                          'A comida favorita do Kuro é banana',
                          'Kuroobi é um oficial dos Piratas do Arlong e ex-membro dos Piratas do Sol',
                          'Sengoku nasceu no South Blue',
                          'Chopper experimentou algodão doce pela primeira vez durante o Davy Back Fight',
                          'Há um tritão na família Donquixote',
                          "O nome do navio que o Mr.1 e a Miss Doublefinger usavam em suas operações era 'Kill Sassoon'",
                          'Koala é um humano que pode usar o karatê tritão',
                          'Antes dos eventos da guerra, Laffitte tinha uma recompensa de 42,200,000 de berry',
                          'A comida favorita do Doflamingo é lagosta',
                          'Carina era amiga da Nami no East Blue',
                          'A atual recompensa do Bepo é de 500 berry',
                          '[GLA] Personagens diamante são 7% mais fortes que personagens ouro',
                          'Van Augur, o supersônico, é um Sniper dos Piratas do Barba Negra e um excelente atirado',
                          'Momoo desenvolveu um trauma a respeito do Luffy e do Sanji, sofrendo um ataque de pânico só de vê-los',
                          'Edward Newgate é loiro',
                          'Sadi nasceu na Grand Line',
                          'Tamago perdeu o olho esquerdo para o Pedro',
                          "Doflamingo e Viola tiveram uma 'complexa' relação amorosa",
                          'Jinbe é um membro dos Piratas do Chapéu de Palha e ex-Shichibukai',
                          'Os Unluckies nasceram na Grand Line',
                          '[GLA] Nico Robin pode construir pontes com a habilidade Campo de Flores',
                          'Tamago comeu a Tama Tama no Mi, que o permite ciclar entre diferentes formas',
                          'Kenbunshoku no Haki garante ao usuário o sexto sentido do mundo ao seu redor e habilidades precognitivas limitadas',
                          'O Exército Revolucionário foi fundado em algum momento entre a morte de Roger e o nascimento de Luffy',
                          'Catarina Devon é a capitã do sexto navio, liderando a sexta frota do Teach',
                          '[GLA] Baratie é o primeiro local em que você pode construir um navio nível 3',
                          'Daddy Masterson é um personagem non-canon',
                          "Nico Robin é referida como 'Luz da Revolução' pelo Exército Revolucionário",
                          'A primeira recompensa da Nico Robin foi de 79,000,000 de berry, a mesma quantia de sua mãe Nico Olivia',
                          'Gin é um pirata e membro dos Piratas do Krieg',
                          'Jinbe é o timoneiro dos Piratas do Chapéu de Palha',
                          'Smoker é usuário do Haki do Armamento e da Observação',
                          'A recompensa do Killer é de 200,000,000 de berry',
                          '[GLA] É possível fazer missões diárias de Tritão em Cocoyasi Village',
                          'Rebecca pode usar o Kenbunshoku no Haki',
                          'Pekoms comeu a Kame Kame no Mi, que o permite se transformar em uma tartaruga, dando a ele um casco duro como diamante',
                          '[GLA] Você precisa vencer com um time de usuários de Fruta do Diabo para completar a conquista da Base da Marinha',
                          'Apesar da aparência deles, Masira e Shoujo são humanos',
                          'Lucky Roo foi quem originalmente conseguiu a Gomu Gomu no Mi de um navio pirata inimigo',
                          'Eustass Kid perdeu seu braço esquerdo',
                          'Izo nasceu em Wano',
                          '[GLA] Não é possível subir no segundo andar da loja do Ippon-Matsu em Loguetown',
                          'Nico Robin também é conhecida como Miss Allsunday',
                          '[GLA] Mohji perde energia enquanto está em batalha',
                          'Enel está na Lua',
                          '[GLA] O Kit de Reparo 1.0 restaura 600 pontos de vida do seu navio por segundo',
                          'Buffalo nasceu no North Blue',
                          'A cera do Mr.3 é tão dura quanto o aço',
                          'Avalo Pizarro era originalmente rei de um país no North Blue',
                          'Haki é um misterioso poder que se encontra dentro de todos os seres vivos do mundo',
                          'Trafalgar Law é o capitão e doutor dos Heart Pirates',
                          'A recompensa do Donquixote Doflamingo é de 340,000,000 de berry',
                          'O nome verdadeiro do Mr.4 é Babe, provavelmente em referência ao famoso jogador de baseball Babe Ruth',
                          'Boa Marigold e Boa Sandersonia têm Haki da Observação e do Armamento',
                          'Sugar ficou permanentemente traumatizada com o rosto do Usopp, tornando-se um trauma incurável',
                          'Oars é um gigante',
                          '[GLA] O stash VIP tem espaço para 100 itens',
                          '[GLA] Gear Third é a habilidade mais forte do jogo em termos de poder',
                          'Sanjuan Wolf é o capitão do sétimo navio, liderando a sétima frota do Teach',
                          'Salome é uma serpente fêmea',
                          '[GLA] Camisa de Tritão é o item mais caro que o Genzo vende e custa 10000 berry',
                          'Diamante é usuário do Haki da Observação e do Armamento',
                          '[GLA] Nico Robin pode construir pontes com a habilidade Delphinium',
                          'Poseidon é uma das armas antigas',
                          'Mr.5 pode comer coisas explosivas e sua comida favorita é pólvora',
                          'Momoo é macho',
                          'Monkey D. Garp nasceu no East Blue',
                          'A cor do cabelo da mãe da Nico Robin é branco',
                          'Cada um dos quatro principais membros da tripulação do Shanks são de diferentes oceanos',
                          "O Red Hawk do Luffy é uma homenagem ao 'Hiken' do Ace",
                          'Barba Branca nasceu na Sphinx Island no Novo Mundo',
                          'Enquanto a fruta do Borsalino é sobre velocidade, ele é bastante lento quando se trata de falar ou agir',
                          'Crocodile nasceu na Grand Line',
                          '[GLA] Há um mapa na casa da Nojiko',
                          'Doc Q é o médico dos Piratas do Barba Negra',
                          'A dubladora do Chopper foi alterada em alguns episódios',
                          '[GLA] Capone Gang Bege é o único personagem que pode convocar dois subordinados sem esperar o tempo de recarga',
                          '[GLA] Existem dois baús de ouro em Loguetown',
                          'Dorry nasceu em Elbaf',
                          'Nico Robin é conhecida como a Criança Demônio',
                          '[GLA] O Kit de Reparo 3.0 restaura 1800 pontos de vida do seu navio por segundo',
                          '[GLA] Há uma prisioneira chamada Tina no Arlong Park',
                          'A recompensa do Lao G era de 61,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai',
                          'Mihawk tornou-se famoso antes da Grande Era dos Piratas sequer começar',
                          'Neptune é um personagem do One Piece',
                          'Killer é um pirata do South Blue e membro do Kid Pirates',
                          'A recompensa do Gecko Moria é de 320,000,000 de berry',
                          '[GLA] A rotação semanal muda toda sexta-feixa',
                          "A espada de Shiryu é uma Meito chamada 'Raiu'",
                          '[GLA] Existem 28 conquistas para completar no modo história das missões especiais do East Blue',
                          '[GLA] Jose, discípulo de Carmen, está na biblioteca de Loguetown',
                          "Otohime era conhecida pela alcunha 'Encarnação do Amor' devido à sua incrível bondade e busca pela paz entre diferentes espécies",
                          'Portgas D. Ace era o comandante da segunda divisão dos Piratas do Barba Branca',
                          'Diamond Jozu comeu a Kira Kira no Mi, fazendo com que ele se transforme em um diamante humano com uma resistência incomparável',
                          '[GLA] Fuyuki é o avô do Sora',
                          'Miss Valentine nasceu no West Blue',
                          'A recompensa do Gladius era de 31,000,000 de berry antes de ser congelada em razão do Doflaming ter se tornado um Shichibukai',
                          'Kizaru nasceu na Grand Line',
                          'O Yonkou Shanks é conhecido por ser o Capitão dos Piratas do Shanks',
                          'Woop Slap é prefeito de Orange Town',
                          'Capangas do Capone ficam imunes durante o Big Father',
                          'Buggy tem a maior recompensa ente os Shichibukais',
                          'Doflamingo matou Gekko Moria',
                          'A Recompensa do X-Drake é de 220,200,207 de berry',
                          'Jango é um marinheiro e o ex-capitão do Black Cack Pirates',
                          'Mihawk possuiu apenas um tradutor no anime',
                          'Erik é um personagem non-canon de One piece',
                          '[GLA] Você precisa alimentar um prisioneiro na Quest da Ririka',
                          'Shanks é um membro dos Yonko que governam o novo mundo e é capitão dos piratas do Shanks',
                          'Catarina devon nasceu na grand line',
                          'O Doflamingo foi o primeiro personagem a despertar sua fruta do diabo',
                          '[GLA] Kumo Island é recomendada para jogadores de level 64 a 70 in the game minimap',
                          'Diamond Jozu nasceu na Grand Line',
                          'Ace comeu a Mira Mira no Mi',
                          'Nerfetari Vivi faz parte do bando dos chapéu de palha',
                          '[GLA] você pode encontrar 8 instacias do black market em eastblue',
                          '[GLA] Killer causa 4x mais sangramento usando Bloody Cuts ou Kira Nokogiri',
                          'O Primeiro Beijo conhecido de Sanji foi com Violet',
                          "Buchi usa a skill 'take the lead'  para chamar o Sham",
                          'Boodle é prefeito de Syrup Village',
                          '[GLA] Loguetown é recomendada para jogadores de level 56 a 70 no minimapa do game',
                          'Bartholomew Kuma tinha a fruta do diabo do espelho',
                          '[GLA] Island of Rare Animals é recomendada para jogadores do level 38 a 52 no minimapa do jogo',
                          'Charlotte Linlin é filha da Big Mom',
                          '[GLA] Lâmina Escondida é um item que pode ser usado por todas as Classes',
                          'A Recompensa de Hatchan é de 7,000,000 de berry',
                          'O Prefeito de Foosha Village é quem da o Tutorial do início do game',
                          'One Piece é o maior anime do mundo',
                          'Chess nasceu no West Blue',
                          'Smoker nasceu no east blue',
                          '[GLA] Em geral os emotes são liberados level 40',
                          'Luffy ganhou sua cicatriz por causa de um tigre em Foosha Village',
                          '[GLA] Carne de Porco Gourmet é a comida mais demorada para cozinhar no baratie. Demora 8 Minutos',
                          'Pearl é o comandante da segunda unidade dos Piratas da Armada Pirata',
                          'Tralfagar Law perdeu um braço durante o Time-Skip',
                          'Alvida é a antiga Capitã dos piratas do Buggy',
                          'Baby 5 Comeu a Boku Boku no Mi',
                          'Eustass Kid perdeu seu braço direito',
                          'Inazuma nasceu no North Blue',
                          'Dracule Mihawk é um membro dos piratas do Ruivo',
                          'Boa Hancock é capitã das Piratas Kuja e a segunda mulher membro dos Shichibukai',
                          'Boa Hancock tem mesma dubladora da Reiju',
                          '[GLA] O Pearl é o primeiro inimigo a se enfrentar na Pirata Armada',
                          'Paggy é um caçador de recompensa que aparece no Arquipélago Sabaody',
                          'Van Augur nasceu no West Blue',
                          'Os Smiles eram feitos pelo Donquixote Doflamingo',
                          '[GLA] Quando Bonney usa seu poder Umbridled, ela transforma todos ao seu redor em bebês e também ficam imunes por 9 segundos',
                          'Sanji foi o quinto membro a se juntar aos Piratas do Chapéu de Palha',
                          '[GLA] Monkey D. Luffy pode quebrar paredes com a habilidade Gomu Gomu no Ono',
                          'Squard nasceu em North Blue',
                          'Arlong possui um cabelo roxo',
                          '[GLA] O NPC Sora em Samui Island e uma menina',
                          'Crocodile estava interessado na arma urano',
                          'Smoker é conhecido como caçador cinza',
                          'Pagaya è uma estrela do mar e conhecida como professor',
                          'Inazuma nasceu no east blue',
                          'Ninjin era ex-capitão dos piratas usopp',
                          'Frank é o mais alto da tripulação',
                          'A recompensa de um pirata reflete a força dele',
                          'Donquixote Doflamingo é capitão dos piratas Donquixote',
                          'Charlotte Shujan é filho da BigMom',
                          '[GLA] A habilidade de nivel 100 do Arlong, Shark On Tank, imobiliza o inimigo',
                          'Caribou nasceu na grand line',
                          'Duval é o irmão de sanji',
                          'Existem três tipos de haki para todo mundo',
                          'A recompensa do Urouge é de 100,000,000 de berry',
                          'Johnny e Yosaku nasceram no East Blue',
                          'Genzo nasceu no North Blue',
                          'Em termos simples, Haki é a habilidade de sentir energia espiritual (busoshoku), usar força espiritual (Haoshoku) e dominar inimigos (Kenbunshoku)',
                          'Bepo não é um mink',
                          'O verdadeiro nome de Miss Doubleflinger é Paula',
                          'Monkey D. Garp é o verdadeiro pai de luffy',
                          'Pappag é um caçador de recompensas que apareceu no arquipelago sabaody',
                          'Madame Shyarly é uma das unicas irmãs do Arlong',
                          'A recompensa de Daz Bones é de 70,000,000 de berry',
                          'Shanks tem uma cicatriz no olho direito',
                          '[GLA] Barba Negra tem as seguinte classes: Especialista, Bruiser e atirador, a ultima é porque ele tem um revolver',
                          'Gin é capitão dos piratas Gin',
                          '[GLA] Você precisa derrotar 50 cobras na missão do Coby',
                          'A recompensa de Olivia é de 79,000,000 de berrys, o mesmo que sua filha Nami recebeu depois',
                          'Chopper é um guaxinim que comer a fruta human-human',
                          '[GLA] Henry Needle, Henry Blazer, henry Striper, Henry Ford são nomes de algumas habilidades do Niji',
                          '[GLA] Leo, discipulo de Carmem esta na biblioteca de loguetown',
                          'Miss Valentine nasceu na Grand Line',
                          'Trafalgar Law é membro dos chapeu de palha',
                          'Dentre os piratas do chapeu de palha, Luffy é o favorito de Eiichiro Oda',
                          'Buffalo nasceu no South Blue',
                          'Sengoku comeu a Bito Bito no mi, uma fruta do tipo zoan mitica',
                          'A terceira recompensa do Monkey D. Luffy foi de 400,000,000 de berry',
                          'A recompensa de Boa Hancock e de 79,000,000,00 de berry',
                          'Arlong ja foi escravo',
                          '[GLA ]Você precisa vencer com um time de especialistas para completar a conquista dos Piratas do Arlong',
                          'Franky é um robô',
                          'Franky destruiu a planta de Uranus',
                          'Franky foi o primeiro ciborgue a aparecer na série',
                          'Miss Goldenweek fez dupla com o Mr.2 em razão das habilidades dela de pintar as criações de cera, tornando-as mais realistas',
                          'A recompensa do Mr.2 é de 30,000,000 de berry',
                          'Machvise comeu a Hon Hon no Mi',
                          'Marco comeu a Pori Pori no Mi, tipo: Fenix, uma Zoan Mítica',
                          '[GLA] O Kit de Reparo 3.0 restaura 1000 pontos de vida do seu navio por segundo',
                          'Monkey D. Garp nasceu em South Blue',
                          'Issho comeu a Fuji Fuji no Mi, que permite manipular a gravidade',
                          'Zoro empunhou menos de 8 espadas no anime',
                          'Trafalgar Law já foi um escravo',
                          '[GLA] É possível criar poção media de exp, poção grande de exp e poção pequena de exp no mercado negro',
                          'Dororo é um personagem de One Piece',
                          '[GLA] Nanashaku Jitte é um item de nivel 70 que pode ser usado por todas as classe',
                          '[GLA] A habilidade Motivation aumenta a velocidade do Luffy por 4 segundos e concede bônus de força no próximo ataque',
                          'Monkey D. Luffy nasceu em Nanko Village',
                          'Monkey D. Luffy foi a única pessoa a escapar de Impel Down na história',
                          'Laboon é femea',
                          'Kuzan nasceu na Grand line',
                          'Tamago comeu a Cuma Cuma no Mi, que o permite ciclar em diferentes formas',
                          "Doflamingo e Baby five tiveram uma 'complexa' relação amorosa",
                          'Boa Marigold e Boa Sandersonia tem somente Haki do armamento',
                          '[GLA] Trafalgar Law não pode usar nenhuma habilidade quando esta fora do room',
                          'Damaro Black, Manjaro, Chocolat, Drip, Turco, Cocoa, Mountmountain e Nora Gitsune são os nomes verdadeiros da falsa tripulação dos chapeus de palha',
                          '[GLA] Piiman, um dos piratas do usopp, da algumas missões em Syrup Villag',
                          'Antes dos eventos da guerra, laffitte tinha uma recompensa de 42,000,000 de berry',
                          "O principal navio do exercito revolucionario é chamado de 'Viento Granmar'",
                          "[GLA] Marshall D. Teach ganha 30% de ataque e perde metade da armadura quando sua passiva é ativada",
                          '[GLA] Não é possível entrar na mansão de Kaya',
                          'Smoker comeu a Doku Doku no Mi',
                          'Doutor Hiriluk nasceu em Drum Island',
                          '[GLA] É possivel criar medalhas dinâmicas de ouro por 15 moedas piratas no mercado negro',
                          '[GLA] O NPC Magra pede 4 orelhas de lobo na missão dele em Foosha Village',
                          '[GLA] Não há um Marine Announcer em Conomi Island',
                          '[GLA] Bastão do Rei Macaco é um item que pode ser usado apenas por lutadores',
                          '[GLA] Atualmente existem somente 10 personagens Bronze disponíveis',
                          '[GLA] Snowflakes é o nome do animal de estimação do Sora',
                          '[GLA] Pufferfish e Shark são considerados monstros nível 3',
                          '[GLA] Todos os chapeus de palha possuem um skin de Strong World',
                          '[GLA] Sanji pode se curar com a habilidade Master Cook',
                          "O nome do navio que os piratas Donquixote usaram nos dias deles no North Blue era 'Flamingo Family'",
                          '[GLA] você pode construir uma caixa de musica por 200 moedas piratas no mercado negro',
                          'Magellan comeu a Moku Moku no Mi',
                          'O nome verdadeiro da Miss Merry Christmas é Marianne',
                          'A recompensa do Mont Blanc Cricket é desconhecida',
                          'Bartholomew Kuma era conhecido como um Pacifista',
                          'Wapol nasceu no North Blue',
                          '[GLA] Você não pode trocar sua página de equipamentos em uma Zona Segura',
                          'A comida favorita da Sugar é laranja',
                          'A recompensa do X-Drake é de 220,200,000 de berry',
                          'Miss Goldenweek nasceu no West Blue',
                          'Trafalgar Law é conhecido como o Cirurgião Mortal',
                          'Após ser diagnosticado com sua doença, Gol D. Roger levou dois anos para encontrar sua recompensa',
                          '[GLA] O Kit de Reparo 1.0 restaura 450 pontos de vida do seu navio por segundo',
                          'Oars é um meio-gigante',
                          '[GLA] Baratie é recomendado para jogadores do level 42 a 50 no minimapa do jogo',
                          '[GLA] Você pode encontrar 8 entradas para o Mercado Negro no East Blue',
                          "Nico Robin é referida como 'Demônio da Revolução' pelo Exército Revolucionário",
                          'Kanjuro comeu a Draw Draw no Mi, que o permite trazer à vida tudo o que ele desenha',
                          'Capone Gang Bege é capitão do Castle Tank Pirates e também um dos doze piratas classificados como a Pior Geração',
                          'A recompensa do Pica era de 100,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai',
                          'Pekoms tem uma impressionante recompensa de 300,000,000 de berry',
                          '[GLA] É possível criar Medalhas Dinâmicas de Diamante por 40 Moedas Piratas no Mercado Negro',
                          'Mr.3 queria trair Crocodile desde o início do arco',
                          'Vergo pode cobrir quase seu corpo inteiro com Haki',
                          'O nome verdadeiro da Baby Five é Babi',
                          'Catarina Devon caça qualquer HOMEM que ela acha atraente e decapita a cabeça deles para adicioná-las à sua coleção pessoal',
                          'A recompensa do Fisher Tiger era de 200,000,000 de berry',
                          'O gênero de Surume é feminino',
                          'Issho nasceu no South Blue',
                          '[GLA] Há uma prisioneira chamada Tita no Arlong Park',
                          '[GLA] Calça de Tritão é o item mais caro que o Genzo vende e custa 10000 berry',
                          'Perona tem o mesmo dublador da Koala',
                          'Mohji é um pirata e capitão dos Piratas Leões',
                          'Gol D. Roger usava um chapéu similar ao do Luffy',
                          'Atualmente o Monkey D. Luffy tem a maior recompensa conhecida',
                          'A recompensa do Gladius era de 30,000,000 de berry antes de ser congelada em razão do Doflaming ter se tornado um Shichibukai',
                          '[GLA] Um personagem Diamante precisa de mais medalhas para ter suas estrelas melhoradas do que um personagem ouro',
                          '[GLA] Para iniciar a quest do Ripper em Shells Town, você precisa primeiro completar a quest do Helmeppo',
                          '[GLA] Em Conomi Island você pode encontrar os seguintes inimigos: Moles, Wolves, e Small Moles',
                          "O nome do navio que o Mr.5 e a Miss Valentine usavam em suas operações era 'Bomb Rock Candy'",
                          '[GLA] A habilidade Liberation, do Marshall D. Teach, tem dois segundos de tempo de recarga e 10 de poder',
                          "A alcunha do Laffitte, 'Shinigami' ou deus da morte, vem do fato dele gostar de brincar com a vida das pessoas, assim como um shinigami",
                          'Hody Jones é o capitão dos Piratas Homens-Peixe',
                          '[GLA] Nami pode criar somente 3 núvens simultaneamente',
                          '[GLA] Você precisa vencer com um time de tanques para completar a conquista da Base da Marinha',
                          '[GLA] Existem Bronze berry, Silver berry, Gold berry e Diamond berry',
                          'Jinbe foi o nono membro a entrar na tripulação dos Chapéus de Palha',
                          'Gin tem o mesmo dublador do Kuro',
                          'Pica é usuário do Haki do Armamento apenas',
                          'Doc Q é o médico dos Piratas do Barba Branca',
                          '[GLA] O Kit de Reparo 2.0 restaura 22.000 pontos de vida do seu navio em 30 segundos',
                          '[GLA] Shanks mata inimigos fracos instantaneamente com a habilidade Kenbunshoku Haki',
                          'Pekoms comeu a Tame Tame no Mi, que o permite se transformar em uma tartaruga, dando a ele um casco duro como diamante',
                          'O nome verdadeiro do Hatchan é Hatchi',
                          '[GLA] Backflips e habilidades de evasão concedem imunidade a dano e imobilizações',
                          'Sengoku nasceu no North Blue',
                          'O dragão contra o qual Luffy e os outros lutaram em Punk Hazard foi criado artificialmente por CAESAR em um Laboratório em Punk Hazard',
                          '[GLA] Existem 30 conquistas para completar no modo história das missões especiais',
                          'Trafalgar Law comeu a Pika Pika no Mi',
                          '[GLA] Jinbe é o único personagem Diamante com a classe Tanque',
                          '[GLA] Hideka é a avó do Sora',
                          'A recompensa do Buffalo é de 15,000,000 de berry',
                          'A recompensa do Gin é de 10,000,000 de berry',
                          'A recompensa da Miss Valentine é de 7,000,000 de berry',
                          '[GLA] Fire Pearl é o nome da passiva do Pearl',
                          '[GLA] Uchimizu é uma habilidade que pode ser usada por Jinbe, Chew e Arlong',
                          'Após os eventos em Punk Hazard, Smoker se tornou oficialmente o líder da G-4',
                          'A recompensa do Buffalo é de 13,000,000 de berry',
                          'Barba Negra nasceu no North Blue',
                          'Caesar comeu a Shiro Shiro no Mi',
                          'Masira e Shoujo têm uma recompensa de 36,000,000 e 23,000,000 de berry, respectivamente',
                          'Diamante foi o primeiro a encontrar a Ito Ito no Mi quando era um criminoso',
                          'Enel comeu a Gura Gura no Mi',
                          'Tamago perdeu o olho direito para o Pedro',
                          'Crocodile foi o segundo oponente a derrotar Luffy em uma batalha',
                          '[GLA] Morgan é o único boss de Missão Especial que também é um NPC	',
                          'Scratchmen Apoo é da tribo longarm, um infâme pirata com tema de música e capitão dos Piratas On Music',
                          'A barreira do Bartolomeo quebrou somente uma vez durante o anime',
                          'Funkfreed é o nome do elefante do Spandam',
                          'Os Yeti Cool Brothers são parte de uma subespécie desconhecida de humanos',
                          'A recompensa do Zoro é maior que a do Sanji',
                          '[GLA] Jango é o único boss de Missão Especial que também é um NPC',
                          'Kid e Killer são amigos de infância. Juntos, formaram os Piratas do Killer',
                          '[GLA] Sapi é o NPC que vende Atum em Cocoyasi Village',
                          "Otohime era conhecida pela alcunha 'Reencarnação do Amor' devido à sua incrível bondade e busca pela paz entre diferentes espécies",
                          'Masashi Kishimoto é o criador do One Piece',
                          '[GLA] Você precisa vencer com um time de mulheres para completar a conquista dos Black Cat',
                          'Tsuru nasceu no East Blue',
                          '[GLA] Meito: Shigure é um item que pode ser usado somente por cortantes',
                          'Boa Hancock nasceu no North Blue',
                          'Kuzan decidiu se cegar porque haviam muitas coisas que ele não queria ver',
                          'A recompensa do Senor Pink era de 56,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai',
                          '[GLA] Nefertari Vivi pode fazer uma dança sexy para motivar seus aliados, aumentando o ataque e a defesa deles por 15 segundos',
                          '[GLA] Nico Robin não pode construir pontes com a habilidade Delphinium',
                          'Benn Beckman NÃO é o personagem mais inteligente que apareceu na saga do East Blue',
                          'A recompensa do Jinbe era de 200,000,000 de berry antes dele se tornar um Shichibukai',
                          '[GLA] Sanzen Sekai é a habilidade mais forte do jogo em termos de poder',
                          'Catarina Devon é a capitã do quinto navio, liderando a quinta frota do Teach',
                          'Laffitte cresceu no West Blue, onde se tornou Marinheiro',
                          "Kin'emon é usuário de Haki do Armamento apenas",
                          '[GLA] Você precisa vencer com um time de especialistas para completar a conquista dos Piratas da Alvida',
                          'Antes dos eventos da guerra, Van Augur tinha uma impressionante recompensa de 60,000,000 de berry',
                          '[GLA] Monkey D. Luffy têm as seguintes classes: Bruiser, Lutador e Tanker',
                          'Killer perdeu um braço no Timeskip',
                          'A Sniper Island está localizada na Grand Line',
                          'Shanks foi o primeiro dono do chapéu de palha',
                          'Johnny e Yosaku nasceram no West Blue',
                          'Akainu nasceu na Grand Line',
                          'Killer é um pirata do North Blue e membro do Kid Pirates',
                          'Vasco Shot é o capitão do sétimo navio, liderando a sétima frota do Teach',
                          'Depois do timeskip o Franky é o mais alto dos Piratas do Chapéu de Palha',
                          '[GLA] Você precisa vencer com uma equipe de HOMENS para completar a conquista da Armada Pirata',
                          'Barba Branca comeu a Goro Goro no Mi',
                          'O nome verdadeiro do Mr.4 é Derek, provavelmente em referência ao famoso jogador de baseball Derek Jeter',
                          'Foxy comeu a Soro Soro no Mi',
                          'O Exército Revolucionário foi fundado após o nascimento do Luffy',
                          'Aisa nasceu com um Haki do Armamento avançado',
                          'Otohime tinha um Haki da Observação e do Armamento muito desenvolvido, o que a permitia entender profundamente a emoção dos outros',
                          '[GLA] O PvP na Grand Line será opcional',
                          'Stussy nasceu no West Blue',
                          'Como um dos principais membros do Exército Revolucionário, Koala tem uma recompensa de 320,000,000 de berry',
                          '[GLA] Sabo é o nome da criança que a Nojiko pede para ajudar no Arlong Park',
                          'A recompensa do Demaro Black é de 26,300,000 de berry',
                          'Rosinante foi o primeiro Corazón',
                          'Rosinante comeu a Shiu Shiu no Mi',
                          'Momoo agora é oficialmente considerado um animal de estimação dos Piratas do Arlong',
                          '[GLA] Quando Sanji cura uma mulher, ele fica motivado e recebe um bônus de velocidade e ataque por 10 segundos',
                          'Todos os quatro principais membros da tripulação do Shanks são do mesmo oceano',
                          'Enel e seus sacerdotes conquistaram a lua',
                          'Sanjuan Wolf é o capitão do quinto navio, liderando a quinta frota do Teach',
                          '[GLA] Atualmente Pearl é o único personagem com três classes: Tanque, Especialista e Lutador',
                          'A recompensa do Diamante era de 100,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai',
                          '[GLA] No tutorial do jogo, o NPC que passa instruções para você é o Woop Slap, o prefeito de Foosha Village',
                          'Ryuma tinha a sombra de um lendário samurai de Wano',
                          'Bellemere encontrou a Nami e a Nojiko no Reino de Oykot, no West Blue',
                          'A recompensa do Machvise era de 10,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai',
                          'Hatchan é um ex-oficial dos Piratas do Sol e membro dos Piratas do Arlong antes disso',
                          '[GLA] Os Kits de Reparo 1.0, 2.0 e 3.0 são vendidos na loja do Mercado Negro pelos respectivos valores: 30, 90 e 180 berry',
                          'A recompensa da Miss Goldenweek é de 30,000,000 de berry',
                          'A cor do cabelo da Miss Valentine é verde',
                          'Python é o nome da espada do Shanks',
                          'Enel está em Marte',
                          'Portgas D. Ace era o comandante da segunda divisão dos Spade Pirates',
                          'O nome verdadeiro do Trebol é John Trebol',
                          'Benn Beckman é o vice-capitão dos Piratas do Shanks',
                          'Doc Q carrega uma grande lança como arma',
                          'Brook foi o último membro a entrar na tripulação dos Chapéu de Palha',
                          'A recompensa do Foxy é de 25,000,000 de berry',
                          'Shiryu é o capitão da terceira frota do Teach',
                          'Benn Beckman nasceu no East Blue',
                          'Basil Hawkins é um pirata infâme do North Blue conhecido como o Mago e capitão dos Piratas do Mago',
                          'A maior recompensa conhecida é de 2,257,600,000 de berry',
                          'Lucky Roo nasceu no North Blue',
                          'Nami conseguiu o Clima-Tact em Drum Island',
                          'Crocodile estava atrás da Uranus, uma das armas antigas',
                          'Sugar ficou permanentemente traumatizada com o rosto do Zoro, tornando-se um trauma incurável',
                          'A recompensa do Lao G era de 60,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai',
                          'Pandaman está na tripulação do Trafalgar Law',
                          'Miss Doublefinger nasceu no South Blue',
                          '[GLA] Daddy McShooty é um inimigo em Loguetown',
                          'A recompensa do Mr.3 é de 23,000,000 de berry',
                          "O navio que a Hancock e as Piratas Kuja navegam é chamado de 'Aroma Snake'",
                          'Crocodile nasceu no North Blue',
                          '[GLA] Muggy Dama é a habilidade que o Buggy libera no nível 100',
                          'Benn Beckman não tem uma recompensa',
                          '[GLA] Buchi pode usar a habilidade Take the Lead para chamar Sham para lutar ao lado dele',
                          'Mihawk não é o único com uma recompensa desconhecida entre os Shichibukai',
                          'A recompensa do Jinbe é de 439,000,000 de berry',
                          'Marco era o comandante da Segunda Divisão e mão direita do Barba Branca',
                          '[GLA] Em regra, a quinta habilidade do personagem é desbloqueada no nível 25',
                          '[GLA] O Kit de Reparo 3.0 restaura 30.000 pontos de vida do seu navio em 30 segundos',
                          'Hatchan tem 8 braços',
                          'Momoo é fêmea',
                          '[GLA] Alvida Pirates é a única Missão Especial do modo história sem uma versão no modo difícil',
                          'Busoshoku no Haki garante ao usuário um sexto sentido do mundo ao seu redor e habilidades precognitivas limitadas',
                          'Bacura é um usuário da Fruta do Diabo do tipo Zoan',
                          '[GLA] Shanks imobiliza inimigos em volta dele com a habilidade Busoshoku Haki Waves',
                          'A recompensa do Zeff é de 47,600,000 de berry',
                          'A recompensa do Tamago é de 429,500,000 de berry',
                          'O nome verdadeiro da Miss Goldenweek é Drophy',
                          'Shanks nasceu no East Blue',
                          '[GLA] Billy McShooty é um inimigo em Orange Town',
                          '[GLA] Island of Rare Animals é recomendada para jogadores do level 38 a 50 no minimapa do jogo',
                          'Monet tinha uma Fruta do Diabo do tipo Paramecia',
                          'O verdadeiro nome do Mr.3 é Baldino',
                          'Sandai Kitetsu (uma das espadas do Zoro) enferrujou',
                          'Smoker é usuário do Haki do Armamento apenas',
                          '[GLA] Samui Island é recomendada para jogadores do level 18 a 26 no minimapa do jogo',
                          'Diamond Jozu comeu a Mira Mira no Mi, fazendo com que ele se transforme em um diamante humano com uma resistência incomparável',
                          'A recompensa do Kuro é de 6,000,000 de berry',
                          'Bartolomeo tem a Fruta do Diabo Nikyu Nikyu no Mi',
                          'Hancock é a imperatriz do Amazon Lily, motivo pelo qual ela é chamada de Imperatriz Shichibukai',
                          '[GLA] Genzo vende Bandana de Tritão, Calça de Tritão, Anel do Mar e Turbante do Mar por 5.000 berry cada',
                          'Rob Lucci nasceu no West Blue',
                          '[GLA] É possível criar Medalhas Dinâmicas de Prata por 8 Moedas Piratas no Mercado Negro',
                          'Arlong era o capitão dos Piratas do Sol e tinha a maior recompensa do East Blue antes de ser derrotado pelo Monkey D. Luffy',
                          'A mãe do Usopp nasceu no South Blue',
                          '[GLA] Enquanto está em chamas, Pearl tem as seguintes habilidades: Fire Pearl Shot, Fire Present, Fire Pearl Close e Fire Pearl Daitokuten',
                          'Frost é um personagem de One Piece',
                          'Atualmente o cabelo do Arlong é roxo',
                          'Antes dos eventos da guerra, Doc Q tinha uma impressioannte recompensa de 72,500,000 de berry',
                          '[GLA] Orange Town é recomendada para jogadores do level 20 a 30 no minimapa do jogo',
                          "Kin'emon comeu a Tuku Tuku no Mi",
                          'Eric é um pirata non-canon que foi mostrado no anime',
                          "O nome dos navios do Masira e Shoujo é ""Utan Sonar"" e 'Victory Hunter', respectivamente",
                          '[GLA] A habilidade da Robin, Spider Net, pode ser destruída por alguns ataques',
                          'Assim como Kuzan, Smoker deseja acabar com o sistema de Shichibukai',
                          'Tsuru comeu a Washe Washe no Mi',
                          '[GLA] Syrup Village é a única ilha com duas entradas de doca no East Blue',
                          'Vista nasceu na Grand Line',
                          '[GLA] A rotação semanal muda todo sábado',
                          'Luffy tem uma Fruta do Diabo do tipo Logia que tornou seu corpo de borracha',
                          'Momoo desenvolveu um trauma a respeito do Luffy e do Zoro, sofrendo um ataque de pânico só de vê-los',
                          'Masira e Shoujo são irmãos',
                          'Golden Lion Shiki é um personagem non-canon',
                          'Haoshoku no Haki garante ao usuário um sexto sentido do mundo ao seu redor e habilidades precognitivas limitadas',
                          'Kid e Killer são irmãos. Juntos, formaram os Piratas do Kid',
                          'Kuro, também conhecido pelo seu apelido Klahadore, é o capitão dos Piratas Neko',
                          'Franky foi o sétimo membro a entrar na tripulação dos Chapéus de Palha',
                          '[GLA] Cerveja Forte é a melhor comida que você pode comprar de um NPC em termos de cura por segundo para um personagem level 70',
                          'Emporio Ivankov nasceu no West Blue',
                          '[GLA] Alvida, Don Krieg, Gin e Pearl são os únicos bosses de missão especial que não aparecem nos spawns das ilhas',
                          '[GLA] Cocoyasi Village é recomendado para jogadores do level 48 a 60 no minimapa do jogo',
                          'Avalo Pizarro era originalmente rei de um país no West Blue',
                          'Doflamingo é usuário de Haki do Armamento e do Rei apenas',
                          'Franky era originalmente líder da Família Franky e agora é capitão dos Cyborg Pirates',
                          'Avalo Pizarro é o capitão do terceiro navio, liderando a terceira frota do Teach',
                          'A recompensa da Baby Five é de 17,000,000 de berry',
                          'Buggy e Shanks estão na mesma tripulação',
                          '[GLA] Mes é a habilidade mais forte do jogo em termos de poder',
                          'Dracule Mihawk teve apenas um dublador durante todo o anime',
                          'A recompensa do Kuroobi é de 8,000,000 de berry',
                          'Akira Toriyama é o criador do One Piece',
                          'Buffalo nasceu na Grand Line',
                          'Lucky Roo foi um dos últimos membros a entrar na tripulação do Shanks após ele formar os Piratas do Ruivo',
                          '[GLA] Mellorine é o nome da passiva do Sanji',
                          '[GLA] O Kit de Reparo 2.0 restaura 700 pontos de vida do seu navio por segundo',
                          'Barba Branca nasceu na Sphinx Island no North Blue',
                          '[GLA] Picareta de Mineração é um item para cortantes e tanques',
                          'O anime One Piece é o maior já feito',
                          '[GLA] Basil Hawkins pode usar sua passiva chamada The Magician para trocar de lugar com seus fantoches',
                          'A atual recompensa da Boa Hancock é 79,000,000 de berry',
                          'Barba Branca foi o responsável por cicatrizar o olho de Shanks com sua arma de garras',
                          'Gura Gura no Mi é uma Fruta do Diabo do tipo Logia',
                          '[GLA] Você precisa vencer com um time de atiradores para completar a conquista dos Piratas do Buggy',
                          "[GLA] Sayuri, Asuya e Cherry são nomes de NPC's do Baratie",
                          'Masira e Shoujo têm uma recompensa de 23,000,000 e 26,000,000 de berry, respectivamente',
                          'Genzo também é um médico',
                          'Nefertari Vivi é um membro dos Piratas do Chapéu de Palha',
                          'Foi confirmado que Usopp despertou o Haki da Observação durante o arco de Punk Hazard',
                          '[GLA] Em regra, a quarta habilidade do personagem é desbloqueada no nível 18',
                          'Jinbe é o Navegador dos Piratas do Chapéu de Palha',
                          'Baby Five nasceu na Grand Line',
                          'A recompensa da Baby Five é de 23,000,000 de berry	',
                          'Em razão dos seus crimes, Sanjuan Wolf foi preso em Impel Down. O modo que eles encontraram para mantê-lo preso foi através de uma cela gigante no level 7',
                          'Demaro Black, capitão dos Falsos Chapéus de Palha, nasceu no West Blue',
                          'A recompensa do Trebol era de 100,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai',
                          'A recompensa atual do Monkey D. Luffy é de 1,500,000 de berry',
                          '[GLA] Você pode conseguir o item Colar do Saru em qualquer Missão Difícil do East Blue',
                          '[GLA] Em regra, a terceira habilidade do personagem é desbloqueada no nível 10',
                          'Buggy é capitão do Clown Pirates e também colíder da Aliança do Buggy e Alvida',
                          'Trebol tinha uma fruta do diabo do tipo Logia',
                          'Zeff perdeu sua perna esquerda para salvar Sanji',
                          'Luffy derrotou Sabo em um duelo durante a infância',
                          'Kuroobi é um oficial dos Piratas do Sol e ex-membro dos Piratas do Arlong',
                          '[GLA] Slime é um inimigo exclusivo de Loguetown',
                          '[GLA] Kuro causa 25% a mais de dano quando ataca inimigos pelas costas',
                          '[GLA] Helmeppo está localizado no mesmo prédio que seu pai Morgan',
                          'Mr.5 nasceu no West Blue',
                          'Laffitte, O Supersônico, é um atirador extremamente habilidoso dos Piratas do Barba Negra',
                          'A recompensa do Urouge é de 100,000,000 de berry',
                          'Aokiji comeu a Yuki Yuki no Mi',
                          'Jesus Burgess é o navegador dos Piratas do Barba Negra',
                          'A comida favorita do Teach é torta de maçã',
                          "O nome do navio que o Mr.1 e a Miss Doublefinger usavam em suas operações era 'Kill Season'",
                          '[GLA] Luffy recebe menos dano dos ataques do Vinsmoke Niji porque seu corpo tem propriedades de borracha',
                          'Nami foi o terceiro membro a entrar na tripulação dos Chapéus de Palha',
                          'Sanji nasceu no South Blue',
                          'Mr.4 nasceu no East Blue',
                          '[GLA] Spider e Giant Spider são os únicos inimigos em Kumo Island',
                          'Punk Hazard pode ser encontrado com um Log Pose',
                          '[GLA] Capone Gang Bege e seus aliados ficam imunes dentro do Big Father',
                          '[GLA] Capone Gang Bege não libera nenhuma habilidade no nível 100',
                          'A primeira recompensa da Nico Robin foi de 78,000,000 de berry, a mesma quantia de sua mãe Nico Olivia',
                          '[GLA] O level necessário para fazer a Quest do Capitão Morgan é 17',
                          'A comida favorita do Marco é uva',
                          'O projeto da Pluton ainda não foi descoberto',
                          'A recompensa do Mr.5 é de 9,000,000 de berry',
                          'Barba Negra é um Almirante dos Piratas do Barba Negra e membro dos Shichibukai',
                          'Kalgara foi revelado como um usuário de Haki do Armamento',
                          '[GLA] Você pode comprar duas abas extras do Stash. A primeira custa 100.000 berry e a segunda 200.000 berry',
                          '[GLA] É possível criar Medalhas Dinâmicas de Bronze por 6 Moedas Piratas no Mercado Negro',
                          'Madame Shyarly é a irmã do Hatchan',
                          'A maior recompensa conhecida é de 1,500,000,000 de berry',
                          '[GLA] Você pode comprar duas abas extras do Stash. A primeira custa 150.000 berry e a segunda 200.000 berry',
                          '[GLA] Quando Bonney usa sua habilidade Unbridled Power, ela transforma todos à sua volta em bebês e fica invulnerável por 9 segundos',
                          '[GLA] Bugs no jogo devem ser reportados no Discord',
                          'Shojo é um membro dos Rumbar Pirates',
                          '[GLA] Espada Dadao é um item recomendado para nível 10',
                          "A espada do Shiryu é uma Meito chamada 'Rain'",
                          '[GLA] É possível criar Poção Pequena de EXP no Mercado Negro',
                          'Foxy nasceu no East Blue',
                          'Katakuri pode ver 5 minutos no futuro',
                          '[GLA] O sangramento de Killer pode acumular até 4 vezes usando mais Bloody Cuts ou Kira Nokogiri',
                          'O cabelo do Charlotte Cracker é verde',
                          'A recompensa do Mr.4 é de 3,000,000 de berry',
                          'Urouge é também conhecido como Mad Monk. Ele é um pirata de uma ilha do céu e capitão dos Mad Monk Pirates',
                          'Caribou nasceu no West Blue',
                          '[GLA] Anel da Cruz é um item recomendado para nível 50',
                          '[GLA] Em regra, emotes são desbloqueados no nível 40',
                          '[GLA] Kiribachi é um item que pode ser usado por todas as classes, exceto especialista',
                          '[GLA] Erros no jogo devem ser reportados no servidor do Discord',
                          'Dracule Mihawk é um Shichibukai e membro dos Piratas do Ruivo',
                          'O nome verdadeiro do Mr.5 é Rem',
                          'A recompensa dos Shichibukai pode aumentar',
                          'Pagaya é uma estrela do mar que é mascote da Camie e também professor. Ele é o criador de uma linha de moda',
                          'Buggy é um Shichibukai',
                          "A recompensa do Dellinger era de 12,000,000 de berry antes de ser congelada em razao do Doflamingo ter se tornado um Shichibukai",
                          '[GLA] Marshall D. Teach ganha 25% de ataque e perde metade da armadura quando sua passiva é ativada',
                          'Brook está morto há 50 anos',
                          '[GLA] Atum é a melhor comida que você pode comprar de um NPC em termos de cura por segundo para um personagem level 70',
                          '[GLA] Kumo Island é a única ilha sem uma instância do Black Market por perto',
                          '[GLA] Você pode iniciar uma missão diária de derrotar Slimes em Samui Island',
                          'Antes dos eventos da guerra, Jesus Burgess tinha uma recompensa de 200,000,000 de berry',
                          'Monet comeu a Hie Hie no Mi',
                          '[GLA] Você pode craftar uma poção media com 10 poções pequenas nas docas das cidades',
                          '[GLA] Você pode usar a mesa de construção nas docas para transformar 10 poções médias de experiência em 1 poção grande de experiência',
                          '[GLA] Você pode usar a mesa de construção nas docas para transformar 10 poções pequenas de experiência em 1 poção média de experiência',
                          '[GLA] Você pode usar a mesa de construção nas docas para transformar 10 poções pequenas de experiência em 2 poções médias de experiência',
                          '[GLA] Você pode usar a mesa de construção nas docas para transformar 5 poções médias de experiência em 1 poção grande de experiência',
                          ],
            "Respostas": [True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True, True, True,
                          True, True, True, True, True, True, True, True, True, True, True, True,
                          False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False, False, False, False, False, False,
                          False, False, False, False, False, False, False, False,False,False,False,False,]
            }
    return date
